### PR TITLE
[feat] use {@html } to render code blocks more efficiently

### PR DESCRIPTION
**Pull request by dominikg**
Instead of rendering a lot of spans into `<pre><code>...</code></pre>`, render one
```<pre>{@html `highlighted-html`}</pre>```. Especially with larger code content this results in smaller js files when compiling the resulting .svelte component.

Note: I did hack this in, there may be a cleaner way to do it. 
Note2: I did not fix the tests expecting the old output. Do you have a script for fixing these?

### CODE REVIEW

**Comment by dominikg** [comment]
This might be relavant for https://github.com/pngwn/MDsveX/issues/72

Maybe both ways (with @html and without) have their uses. You can always supply a custom highlighter that does it the way you prefer. Question is which way would be a good default.
Personally i'd prefer @html as default, the resulting js is much smaller for big code blocks.

**Comment by pngwn** [comment]
This is a good call, I don't think there is any way for a code block to be dynamic in any way. I _thought_ svelte optimised this away, which it does (to `innerHTML = x`) _unless_ your component is compiled as hydratable, which undoes those optimisations. And as you say the difference is huge.

This opens up a broader discussion about what else could be optimised and whether or not it makes sense to do so. In principle anything that is static markdown _could_ be inserted via `{@html}` but then you would not be able to scope CSS to the generated elements. Code blocks are a good start anyway and make sense.

I'll take a look at this PR (and tests) shortly, thankyou!

**Comment by pngwn** [comment]
Thanks for this, I corrected the highlighting tests to fit the new output and everything is working perfectly. This _does_ only apply when using the built-in highlighting as opposed to when providing your own highlight function maybe that is a reasonable trade-off, that gives people the flexibility to do whatever they want in their highlight functions.

As you mentioned, this also fixes #72 as far as I can tell, no hacks required.

Thankyou!

**Comment by dominikg** [comment]
that was fast. thanks!

**Pull request merged**
