### PR TITLE
Fix playground

### PR DESCRIPTION
**Pull request by pngwn**

### CODE REVIEW

**Comment by pngwn** [comment]
ok this seems to work.

**Comment by brittharr** [comment]
Hi! 🤗  sorry if I'm missing something but is this released to https://mdsvex.com/playground yet?
```
// this ⬇️ is what I see in the source code
{packagesUrl: i="https://unpkg.com"} = t, {svelteUrl: c=`${i}/svelte`}

// but I would expect this ⬇️ from this PR
{packagesUrl: i="https://unpkg.com"} = t, {svelteUrl: c=`${i}/svelte@3.59.2`}
```

**Comment by pngwn** [comment]
Hey hey. It looks like redirect isnt working. I'll take a look at that. 

The correct url is here and should be working: https://mdsvex.pngwn.io/playground

**Comment by pngwn** [comment]
Thanks for flagging this!

**Comment by pngwn** [comment]
Okay, should be working now. Al urls should go to `mdsvex.pngwn.io`

**Comment by brittharr** [comment]
Aha!! That would it explain it, thanks for fixing 😄

**Pull request merged**
